name: After E2E Success
on:
  check_run:
    types: [completed]
permissions:
  checks: read
jobs:
  after-e2e:
    runs-on: ubuntu-latest
    if: >-
      github.event.check_run.conclusion == 'success' && 
      github.event.check_run.name == 'e2e-results-check'
    steps:
      - name: Run post-E2E tasks
        run: |
          echo "E2E tests passed! Running follow-up tasks..."
          echo "Commit SHA: ${{ github.event.check_run.head_sha }}"
          echo "Check Run Name: ${{ github.event.check_run.name }}"
          # Add your post-E2E logic here
          #
      - name: React
        uses: actions/github-script@v6
        with:
          script: |
            console.log('issue number', context.issue.number);
            console.log('event_name', github.event_name);
            console.log('repo.owner', context.repo.owner);
            console.log('repo.repo', context.repo.repo);
            
            const prNumber = github.event_name === 'issue_comment'
              ? context.issue.number
              : null;

            if (prNumber) {
              github.rest.issues.createComment({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `E2E tests completed successfully! ✅`
              });
            }
