name: After Success
on:
  status:
permissions:
  statuses: read
jobs:
  after:
    runs-on: ubuntu-latest
    if: github.event.state == 'success' && github.event.context == 'e2e-test-manual'
    steps:
      - name: Run post-E2E tasks
        run: |
          echo "E2E tests passed! Running follow-up tasks..."
          echo "Commit SHA: ${{ github.event.sha }}"
          echo "Context: ${{ github.event.context }}"
          # Add your post-E2E logic here
          #
      - name: React
        uses: actions/github-script@v6
        with:
          script: |
            console.log('issue number', context.issue.number);
            console.log('event_name', github.event_name);
            console.log('repo.owner', context.repo.owner);
            console.log('repo.repo', context.repo.repo);
            
            const prNumber = github.event_name === 'issue_comment'
              ? context.issue.number
              : null;

            if (prNumber) {
              github.rest.issues.createComment({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `E2E tests completed successfully! ✅`
              });
            }
