name: E2E Test Suite
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, master, develop]
permissions:
    checks: write
    statuses: write
    contents: read

jobs:
  e2e-results:
    runs-on: ubuntu-latest

    steps:
      - name: Run E2E Test (Hello World)
        run: |
          echo "Hello World"
          echo "Running E2E test suite..."
          # Simulate some test time
          sleep 5
          echo "E2E tests completed successfully!"
      
      - name: Create Check Run
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const conclusion = '${{ job.status }}' === 'success' ? 'success' : 'failure';
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'e2e-results-check',
              head_sha: context.sha,
              status: 'completed',
              conclusion: conclusion,
              output: {
                title: 'E2E Test Results',
                summary: `E2E tests ${conclusion === 'success' ? 'passed' : 'failed'}`
              }
            });

