name: E2E Test Suite
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, master, develop]
permissions:
    checks: write
    statuses: write
    contents: read

jobs:
  e2e-results:
    runs-on: ubuntu-latest

    steps:
      - name: Run E2E Test (Hello World)
        run: |
          echo "Hello World"
          echo "Running E2E test suite..."
          # Simulate some test time
          sleep 5
          echo "E2E tests completed successfully!"
      
      - name: Create Status
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: '${{ job.status }}' === 'success' ? 'success' : 'failure',
              context: 'e2e-results',
              description: 'E2E test results'
            });

